from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
TABLES = ROOT / 'outputs' / 'tables'
OUT = ROOT / 'article' / 'overleaf_viviane_revision' / 'sections' / 'generated_supplementary_tables.tex'

def longtable(title, label, header, rows, spec):
    lines=[f'\\subsection{{{title}}}', f'\\label{{{label}}}', '\\small', f'\\begin{{longtable}}{{{spec}}}', '\\caption{' + title + '}\\\\', '\\toprule', header+' \\\\', '\\midrule', '\\endfirsthead', '\\toprule', header+' \\\\', '\\midrule', '\\endhead']
    lines += [row+' \\\\' for row in rows]
    lines += ['\\bottomrule','\\end{longtable}','\\normalsize','']
    return lines

def main():
    sector=pd.read_csv(TABLES/'assets_sector_map.csv').sort_values('symbol')
    assets=sector[['symbol','company_name','sector','subsector']]
    issuer=pd.read_csv(TABLES/'issuer_class_sensitivity_selection.csv').sort_values(['company_name','symbol'])
    loads=pd.read_csv(TABLES/'rmt_top_eigenvector_loadings_core_historical_1998_2025.csv')
    loads=loads.sort_values(['eigen_rank','abs_loading'],ascending=[True,False]).groupby('eigen_rank').head(5)
    null=pd.read_csv(TABLES/'rmt_circular_shift_null_1000.csv')
    perm=pd.read_csv(TABLES/'sector_label_permutation_test_10000.csv').iloc[0]
    forecast=pd.read_csv(TABLES/'forecast_validation_selected_test_metrics_by_asset_2006_2025.csv').sort_values(['horizon','model','symbol'])
    lines=['% Auto-generated by scripts/python/21_generate_supplementary_tables.py.','\\noindent All numerical entries below are generated from the CSV files named in the captions.']
    lines += longtable('Asset universe','tab:app_universe','Symbol & Company & Macro-sector & Subsector',[f"{r.symbol} & {r.company_name} & {r.sector} & {r.subsector}" for r in assets.itertuples()], 'llll')
    lines += longtable('Issuer/share-class selection','tab:app_issuer','Company & Symbol & Valid returns & Retained',[f"{r.company_name} & {r.symbol} & {r.valid_return_observations} & {'Yes' if r.retained_in_issuer_panel else 'No'}" for r in issuer.itertuples()], 'llrr')
    lines += longtable('Largest absolute eigenvector loadings','tab:app_loadings','Rank & Eigenvalue & Symbol & Sector & $|u|$',[f"{r.eigen_rank} & {r.eigenvalue:.4f} & {r.symbol} & {r.sector} & {r.abs_loading:.4f}" for r in loads.itertuples()], 'rrllr')
    lines += longtable('Circular-shift RMT null test','tab:app_rmt_null','Rank & Empirical $\\lambda$ & Null 95th pct. & Exceedances & $p$', [f"{r.eigen_rank} & {r.empirical_eigenvalue:.4f} & {r.surrogate_q95:.4f} & {r.exceedances} & {r.monte_carlo_p:.4f}" for r in null.itertuples()], 'rrrrr')
    lines += longtable('Asset-level sector-label permutation test','tab:app_sector_perm','Assets & Pairs & Permutations & $\\Delta_{sector}$ & Null 95th pct. & $p$', [f"{perm.n_assets} & {perm.n_pairs} & {perm.n_permutations} & {perm.observed_value:.4f} & {perm.null_q95:.4f} & {perm.one_sided_monte_carlo_p:.4f}"], 'rrrrrr')
    lines += longtable('Forecast metrics by asset and horizon','tab:app_forecast','Horizon & Model & Set & Asset & MAE & RMSE & QLIKE [95\\% CI]', [f"{r.horizon} & {r.model} & {r.feature_set.replace(' (+Network)',' C').replace(' (+Market/RMT)',' B').replace(' (Classical)',' A').replace('Sequence window','Seq.')} & {r.symbol} & {r.MAE:.4f} & {r.RMSE:.4f} & ${r.QLIKE:.4f}$ [$ {r.QLIKE_ci95_low:.4f}$, ${r.QLIKE_ci95_high:.4f}$]" for r in forecast.itertuples()], 'rlllrrl')
    OUT.write_text('\n'.join(lines)+'\n',encoding='utf-8')
    print(f'Saved {OUT}')
if __name__=='__main__': main()
